version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
